= KISS RPG
Kim Ravn Hansen <kim@krhit.com>
:doctype: book
:toc:
:toclevels: 1
:sectnums:
:sectnumlevels: 1
:homepage: https://krhit.com/kissrpg

Kiss is a set of simple and all-purpose tabletop role playing game rules.  Even
though this document is focussed on the classic medieval fantasy setting, these
rules are highly adaptable for most campaign types.

This work is licensed under a Creative Commons Attribution-ShareAlike 4.0
International License.footnote:[License: https://creativecommons.org/licenses/by-sa/4.0/]
You are free to share and adapt this material for any purpose, including
commercially, as long as you give attribution.

== Dice and Tests

To see if something succeeds, you roll a d10 (called the _base die_) against a
given target number, usually set by the GM. If you equal to or higher than the
target number, you succeed.

Base Die::
When you roll a 10 on your base die, you may roll it again and add the result.
You can do this as long as you keep rolling tens. If your base die has been
modified (for instance, the base die is reduced as a consequence of damage and
stress), this rule still applies as long as you roll the highest possible
number on the die. Adding rerolls like this is called an _open-ended die_ or
exploding die.footnote:[Exploding Dice: https://anydice.com/articles/exploding-dice/]

NOTE: It is not just the base die that can be open ended. Certain traits,
powerups, abilities, equipment and karma uses can make dice open ended. If you
see a die notation with a `+` at the end of it, it means that the die is
open-ended.  For instance, `d6` just means you roll a d6, but `d6+` means you
roll an open- ended d6.

Skill Die::
When a hero is particularly good at doing a specific thing (fighting, swimming,
magic, etc.) she may add a skill die to her roll when she performs those
actions. This is referred to as a skill test. Unless otherwise specified, the
skill die is not open-ended.

Hero Die::
When a hero has become sufficiently advanced and experienced, she gains the
ability to add a hero die to certain rolls. This number of sides on the hero
die depends on how experienced the hero is.


== Karma

Character begins every session with exactly 2 karma points (this is called the
_karma reset_).

If you fail a meaningful roll (i.e. one that actually affects you, the party
and/or the plot), you are awarded a karma point. There are many ways to spend
these points. Some of them are described below:

TIP: High powered campaigns might reset the karma to 3 or 4, while more
realistic campaigns might reset karma to 1 or 0. Some groups might prefer not
to reset the karma pools at all, possibly imposing upper limits on how many
karma points a character can accumulate. In such settings, you could reduce
the number of experience points awarded to the players, forcing them to convert
karma into XP. More on this later.

Exploding roll::
At the cost of 1 karma, before you roll any dice, you can declare that you want
to make the roll _open ended_, meaning that all the dice rolled (base, skill,
and hero) are made open-ended. This can also be applied to damage tests and
other tests that are not normally open ended.

Make a roll _easier_::
At the cost of 2 karma, before you roll any dice, you can declare that you
want to make a test _easier_, meaning that you get roll the entire test twice,
and choose the best outcome. This must be declared _before_ the roll is made.

Make a roll _heroic_::
If you have a hero die, you can spend 1 karma point to add that hero die to
any roll you want. You must declare that you are making a heroic roll _before_
you roll any dice.

Redo a test::
At the cost of 3 karma, you can declare that you want to reroll a failed test.
This is be done _after_ the dice are rolled, but before the GM tells you
whether the test succeeded or not.

Learn from your failures::
You can convert 10 karma points into 1 experience point.

TIP: Some groups might want to impose a limit on how many times you can »learn
from your failures« per session. Others might want to lower the number of XP
awarded per session, instead relying on the players' accumulated karma to be
converted to XP.


== Traits

The first game-mechanical thing to do when creating a new character is to
describe her via traits. You must choose 3 positive traits and 1 negative
trait. You *can* choose more traits if you like, but for every positive trait
you add, you must also add a negative one.

NOTE: In KISS, concepts like attributes, races, background, heritages, etc.
have been replaced by traits.


=== Positive traits

Connected::
Once per session, at the cost of 1 karma, you can declare that you have a vague
connection with someone (maybe you met them, briefly worked for them, etc.).
Additionally, when engaged in social challenges where you can invoke a common
mutual acquaintance, all your rolls are open-ended.

Captain::
You have access to the »Ship Owner« powerup.

Darkvision::
You can see in complete darkness, but only in shades of gray.

Famous::
Once per session, at the cost of 1 karma, you can declare that a given person
knows about you or your family and sees you in a positive light. This makes
all your subsequent social challenges against that person open-ended.

Sprinter::
During combat you can get extra Steps at the cost of 1 karma point per
Step.

Unencumbered::
You can carry 15 load points worth of gear instead of the usual 10.

[[magic-user]]Magic User::
You have access to the <<_magic,magic>> powerups.

Mnemonist::
You can accurately recall anything you have ever seen or heard at the cost of 2
karma point. It only costs you a single karma point to redo tests in challenges
that rely purely on your memory and experience.

Nightvision::
You can see as well in dim light such as starlight or moonlight as if it were
daylight.

Nimble::
Same effect as the »tiny« trait. A character that is both tiny and nimble will
be able to avoid two attacks per scene, provided you have karma to spend.

Overpowered::
You have 8 powerup slots instead of 6.

Polyglot::
When you hear or read a language that was not hitherto known by you, you can
declare that you are familiar with it, enabling you to read, write and speak
it. This can be done once per session and it costs 3 karma points.

Socialite::
Once per session you can overcome a challenge of trust or etiquette by invoking
your background and heritage. Doing so costs one karma point.

Street Smart::
It only costs you a single karma point to redo tests during challenges that
involve shady city connections, finding your way in cities, or evaluating black
market prices.

Strong::
Once per scene you may redo tests that relies heavily and primarily on your
bodily strength. Doing so costs 1 karma.

Stubborn::
When you have the “dying” condition, you are awake and conscious. You can take
actions like any normal character, but doing so costs a karma point.

Tiny::
Once per scene you can completely avoid an attack. If you declare your intent
to avoid the attack before the attacker rolls their dice it costs 2 karma
points. If you want to avoid the attack after the attacker rolls their dice it
costs 3 karma points.

Tough::
Once per scene you can avoid avoid getting a Consequence from a single attack.
Instead of getting a wound and resetting your stress points, your stress points
are set to their maximum value, but you do not get the wound. Doing this costs
one karma point.

Wealthy::
§§§§ How does wealth work when we don't use wealth?

Well-equipped::
You have 10 equipment slots instead of 8.

=== Negative Traits

Addicted::
You have an addiction (alcohol, drugs, sex, gambling). Once per session, at the
cost of 3 karma points, the GM can enforce your addiction to create a conflict,
problem or disadvantage to you or the party.

Average§§§§::
You base die is not open ended.

Diminutive::
The GM can make you reroll your base die in intimidation check in exchange for
1 karma points.

Favor::
You owe a favor to a powerful person, organization, or entity. Once per
session, at the cost of 3 karma points, the GM can invoke this debt to create a
conflict for you or your party.

Hunted::
You are hunted, wanted, or stalked by a creature, person, organization, or
entity. Once per session, at the cost of 3 karma points, the GM can invoke your
stalker or their underlings and create a conflict for you or your party.

Infamous::
Once per session, at the cost of 2 karma points, the GM can rule that you failed
a given social challenge because of your bad reputation.

Infirm::
You easily get sick. At the cost of 2 karma points the GM can make you reroll
the base die of a check to resist disease or poison. At the cost of 3 karma
points the GM can invoke your fragile health to create a situation that is
hazardous to you or your party.

Kleptomaniac::
You are addicted to stealing. Once per session, at the cost of 2 karma points,
the GM can enforce your obsession to create a potential conflict, problem or
disadvantage to you or the party.

Limp::
Your Step Rate is 4 instead of 5. This means only get 4 Steps per combat round
instead of 5. When you exchange your Action for extra Steps, you only get 4
Steps.

Obsessed::
You are obsessed with a person, place, thing or phenomenon. Once per session,
at the cost of 3 karma points, The GM can enforce your obsession to create a
conflict, problem or disadvantage to you or the party.

Poor::
§§§§ Not much stuff.

[[short-legs]]Short Legs::
Same effect as the »Limp« trait. A character that is both Limp and has
Short Legs will only have a Step Rate of 3.

Thickheaded::
Once per session, at the cost of 2 karma points, the GM can enforce your
stupidity and make you redo a relevant test.

Ugly::
Once per session, at the cost of 2 karma points, the GM can rule that you failed
a given social challenge because of your physical appearance.

Uncouth::
Once per scene, at the cost of 3 karma points, the GM can rule that you failed
a given social challenge due to your social ineptitude.

Underpowered::
You have 4 powerup slots instead of 6.

Weak::
You have trouble with forced marches, etc. At the cost of 3 karma points, the
GM can limit your ability to perform demanding physical tasks over long periods
of time. At the cost of 2 karma points the GM can enforce your weakness by
making you redo tests that relies heavily on endurance.

== Skills

There are 6 skill levels:
Untrained,
Novice (d4),
Journeyman (d6),
Advanced (d8),
Expert (d10),
and Master (d12).

*Example:* A character who is a Journeyman in the Melee Combat skill will roll d10 +
d6 whenever she makes a melee attack (provided her base die is d10).

New characters start with 3 skills at the novice (d4) level, 2 skills at the
journeyman (d6) level, and 1 skill at the advanced (d8) level, all other skills
are untrained.

[%header,cols="1,6"]
.Skills
|===
| Skill         | Description
| Acrobatics    | Climb, jump, tumble and stunts.
| Analysis      | Research or investigate an area, item, situation, etc.
| Appraisal     | Estimate price and authenticity of artwork, gems, coins, weapons, armor, buildings, etc.
| Arcana        | Cast magical spells. You must have the *<<magic-user, Magic User>>* trait to learn this skill.
| Athletics     | Run, march, swim, endure physical stress.
| [Craft]       | [craft] can be a craft, art or science such as alchemy, blacksmithing, carpentry, engineering, gambling, masonry or painting.
| Creature Lore | Guestimate an approximation of a key knowledge such as Steps, Stress Threshold, a Skill Score, etc.
| Deception     | Disguise, bluff, lie, impersonate.
| Geography     | Travel routes, local area knowledge, imports/exports, local prices, local laws.
| Healing       | First Aid, identify diseases and poisons.
| History       | Local lore, ancient lore. Knowledge of the old gods, of ancient cultures, races heroes and items.
| Insight       | Gain insight into the motivations and feelings of another person.
| Melee Combat  | Attack with melee weapons.
| Negotiation   | Intimidation, haggling, interrogation.
| Range Combat  | Attack with ranged- and thrown weapons.
| Reaction      | Avoid traps, dodge explosions and other area effects.
| Riding        | Horses, stags, griffins.
| Stealth       | Hide, sneak, camouflage.
| Survival      | Hunting, gathering, direction sense.
| Thievery      | Pick locks, slight of hand.
| Willpower     | Resist interrogation and magical domination.
|===


== Gear

New characters start with 2 items from the Weapons table, 1 item from the
Armors table, and 4 items from the Gear tables.

Load Points::
Items have Load Points that represent how difficult they are to lug around.

Carrying Capacity::
A character can carry 10 load points. Certain traits, spells, enchantments,
can modify the character's carrying capacity.

Equipment Slots::
A character has 8 equipment slots, meaning that she can carry 8 "relevant"
items. Items that are not essential to the game (undergarments, grooming
equipment, love letters from the sweet heart, etc.) or that have negligible
weight (maps, drawings, letters, jewelry) do not not count.

Food, money, ammo::
We do not bother with those things in KISS. Wealth is measured in XP, and XP
can be converted to items.


====
[%header, cols="4,4*^.^"]
.Weapons
|===
| Weapon                        | Load  | Close | Near  | Far

| Unarmed Combat                | 0     | 1     | -     | -
| Knuckledusters                | 1     | d4    | -     | -
| Knives                        | 1     | d4    | d4    | -
| Staves, clubs, batons         | 2     | d6    | -     | -
| Javelins                      | 1     | d4    | d6    | -
| Light swords, axes, spears    | 3     | d8    | -     | -
| Heavy swords, axes, polearms  | 4     | d10   | -     | -
| Short bows, light crossbows   | 2     | -     | d6    | d4
| Long bows, heavy crossbows    | 4     | -     | d10   | d8
| Slings, hand crossbows        | 0     | -     | d4    | -
| Musket pistols                | 1     | d6+   | d4    | -
| Scatterguns                   | 3     | d10+  | d4    | -
| Musket Rifles                 | 4     | 1d4   | d10+  | d6+
|===

*+*      denotes that the die is open-ended. +
*Load*   is the number of Load Points you loose when wearing this armor. +
*Close*  damage the weapon deals to opponents that are Close to you. +
*Near*   damage the weapon deals to opponents that are Near you. +
*Far*    damage the weapon deals to opponents that are Far away from you.
====


====
[%header, cols="4,4*^.^"]
.Armors
|===
| Armor             | Load  | Stress    | Hit   |  Steps

| Unarmored         | 0     | 10        | 8     | ±0
| Leather           | 1     | 11        | 8     | ±0
| Hide Armor        | 2     | 12        | 9     | -1
| Hardened Leather  | 1     | 13        | 8     | ±0
| Scale Mail        | 3     | 13        | 9     | ±0
| Chain Shirt       | 2     | 14        | 9     | -1
| Chain Mail        | 3     | 14        | 10    | -1
| Breastplate       | 3     | 14        | 11    | -2
| Banded Mail       | 4     | 15        | 11    | -2
| Half Plate        | 4     | 15        | 12    | -3
| Full Plate        | 5     | 15        | 13    | -3
| Shield            | 1     | ±0        | +1    | ± 0
| Helmet            | 1     | +1        | ±0    | ± 0
|===

*Load*   is the number of Load Points you loose when wearing this armor. +
*Stress* is how many points of damage you can suffer before suffering a consequence. +
*Hit*    is the target number you need to successfully attack the wearer. +
*Steps*  is the effect on your Step Rate when wearing this armor. +

====

== Powerups

Having chosen traits, the second thing to do is to choose your powerups. You
have 6 powerup slots (meaning that you can choose up to 6 powerups). You get 10
experience points with which to purchase powerups, and you can choose any powerup
that has an XP cost of 3 or lower.

NOTE: In KISS, concepts like money, gear, special items, contacts, special
abilities, spells, etc. are all considered powerups. When you gain experience
from adventuring, you can purchase additional powerups, or increase the oomph
of the ones you already have.


=== Heroism

The heroism powerups boost the characters overall abilities without being
linked to any particular abilities, spells, or items.

==== Lucky
The _lucky_ powerup increases your karma reset value, giving
you more karma every time a new session starts.
[%header, cols="4,3,40a"]
.Lucky Powerup
|===
| Level | XP | Description
| 1     | 2  | Your karma reset value is 3
| 2     | +2 | Your karma reset value is 4
| 3     | +2 | Your karma reset value is 5
|===


==== Take the hit (XP cost: 1)
When one of your opponents attacks one of your allies, you can spend 1 karma
and declare that the opponent attacks you instead. This only works if the
opponent is able to attack you the same way as they intended to attack your
ally.



==== Hero
The _hero_ powerup gives you the ability to add a hero die to your rolls.
The higher level you attain in _hero_, the bigger your hero die.

[%header, cols="4,3,40a"]
.Hero Powerup
|===
| Level | XP  | Description
| 1     | 10  | Your hero die is d4
| 2     | +2  | Your hero die is d4+
| 3     | +3  | Your hero die is d6
| 4     | +4  | Your hero die is d6+
| 5     | +5  | Your hero die is d8
| 6     | +6  | Your hero die is d8+
| 7     | +7  | Your hero die is d10
| 8     | +8  | Your hero die is d10+
| 7     | +9  | Your hero die is d12
| 8     | +10 | Your hero die is d12+
|===


=== Magic
Magic powerups are essentially spells.  Some spells cost karma to cast.  Some
spells power levels can be increased if you pay a lot of karma.  If you don't
have enough karma to cast a spell, you can cast it as a ritual: 15 minutes per
karma point required.  Casting spells as rituals causes one stress point of
damage per karma.

Spells can be instant, sustained, or have a fixed duration.

* Instant spells are fire-and-forget.
* Fixed-duration spells last as long as the duration description of the spell.
* Sustained spells must be sustained by spending a number of Steps each round.
  See the <<Combat>> chapter for more info about Steps.
  All spells that are not instant or do not explicitly have a duration are
  considered to be Sustained.

// End of list

==== Cantrip
Cantrips are seemingly simply effects that can aid the magic user in everyday
situations, but they can actually be extremely powerful, especially at the
higher levels.  Any non-instantaneous effects of cantrips (for instance the
light effects) require concentration.

[%header, cols="4,3,40a"]
.Cantrip Powerup
|===
| Level | XP  | Description

| 1
| 1
|
* Create a small sound originating from a nearby location.
* Light a nearby candle.
* Instantly clean a dirty object no larger than your fist.
* Instantly Heat or cool a meal or a drink.

| 2
| +1
|
* Create a small illusionary image about the size of your fist, located in your
  hand or somewhere else on your person.
* Make an object no larger than your fist shine with the same
  brightness as a candle.
* Instantly clean a part of a dirty surface. The cleaned area can be as large
  as a dinner plate.

| 3
| +1
|
* Repair a break or tear no larger than your fist. This effect also removes
  rust, scratches and wear.
* Telekinetically move nearby object that weighs no more than 
* Make an object no larger than your fist shine with the same brightness
  as a torch.
* Instantly light a bonfire.
* Instantly create one basic meal, including water.
* Open a tiny portal to a personal alternate dimension where you can store
  items no larger than your arm. The items can be retrieved when you cast
  this spell again.

| 4
| +1
|
* Summon a spiritual servant that can do simple tasks such as cleaning,
  sewing, mending. The spiritual servant has the same physical strength as a
  small child, but same size as the caster.
* Instantly create a bonfire, even though you have no fuel.
* Instantly create one "fancy" mean, including water and ale.

| 5
| +1
|
* Tiny hut§§§§.
* Instantly tidy and clean dirty and untidy up room.
* Instantly sort a row of books by author, subject and/or title.
* Permanently make a small object shine with the same brightness
  as a large bonfire.
* Instantly create a luxury banquet for 4 persons, including several courses
  and fine wine.
* Instantly retrieve one item from your personal space directly into your
  hand.

|===



==== Illusion
Illusion spells create images and sounds that appear to be real, but
fundamentally aren't.  At the higher levels, illusions can be so real that they
can inflict damage and otherwise interact with living beings.  Illusions can be
disbelieved at the GMs discretion. It often involves pitting the disbeliever's
Willpower test against the illusionist's Arcana.


[%header, cols="4,3,40a"]
.Illusion Powerup
|===
| Level | XP  | Description

| 1
| 1
|
* Create a small, animated illusory image the size of your head that lasts as
  long as you sustain it.
* Disguise self. Change your clothing, gender, race and physical appearance.
  light sword. You can use your Arcana skill to attack with the weapon.
* §§§§ Message (range: 50 meters)

| 2
| +1
|
* Create an illusory melee weapon that has the same characteristics as a
  light sword. You can use your Arcana skill to attack with the weapon.
* Disguise other. Change clothing, gender, race and physical appearance of an ally in sight.
* Disguise self for 8 hours.
* §§§§ Message (range: 500 meters)

| 3
| +1
|
* Create an illusory ranged weapon that has the same characteristics as a
  heavy crossbow. You can use your Arcana skill to attack with the weapon.
* §§§§ Ephemeral Bolt.
* §§§§ Invoke duplicity.
* Illusory Dwelling.
* Illusory Wall of fire.
* Disguise Other for 8 hours.
* Disguise up to 8 allies in sight.

| 4
| +1
|
* §§§§ Mirror Image (3 · Invoke Duplicity)
* §§§§ Illusory summoned horde of monsters.
* §§§§ Message (no range limit) - costs 1 karma per sentence (about 20 words).
* Disguise up to 8 allies in sight for 8 hours.


|===



=== Equipment

Ship Owner (XP cost: 3, 5, or 8)::
You own a spaceship. The amount of XP you pay for this powerup determines the
size of the ship.

Fancy Item§§§§::
You get a fancy item corresponding to the number of experience points put into this powerup.
It is up to you and the GM to figure out how you get your hands on this item.
If you loose or break this item, you do not get the XP back.

NOTE: that the GM may "give" you an item, but you must still pay a sum of XP in order to be able to
attune to it (use it).



== Combat

There are a number of common terms used in combat. When you understand them
all, you'll have a pretty good idea how com idea how combat works.

=== Initiative
Combat is divided into rounds, in which combatants act in turn.
At the beginning of each round, each side chooses one character to roll
a Reaction skill test. The side with the highest roll gets to go first
that round.

NOTE:: This means that sometimes, one side gets to act twice in a row.

=== Rounds
During a combat round, you have 5 Steps and 1 Action which you can take in any
order. For instance, you can take 3 Steps, your main Action, and then up
to 2 more Steps.

=== Step Rate
Normal characters have a Step Rate of 5. This means that they get 5 Steps each
round, however certain traits can modify the number of Steps you get each
round. For instance, a creature with <<short-legs,Short Legs>> would only have
a Step Rate of 4, meaning that they get 4 Steps every round, and only gain 4
more Steps when they converted their Action to Steps.
Certain items, such as armors and helmets, may further reduce your Step Rate.


=== Steps
The most common use of a Step is to move 1 square in any direction, but there are
more uses than that. You can:
* Spend one Step to move 1 square in any direction.
* Spend 3 Steps to get up from prone position.
* Sustain a spell by expending a number of Steps equalling your Step Rate.

NOTE: Some groups (or encounters) do not use squares, but may instead use a
more narrative based approach. In these cases, you should be able to
expend 4 steps to move from near range to close range of an opponent or expend
8 steps to move from near range to far range of an opponent.

=== Actions
The most conventional use of an action is to attack. However, you can also:
* Spend your Action to attack an adjacent opponent with the Melee Combat skill.
* Spend your Action to attack an opponent with the Ranged Combat skill.
* Spend your Action to cast a spell.
* Spend your Action to get 5 more Steps.

=== Range

There are 3 types of range: _Close_, _Near_, and _Far_.

Close::
An opponent in Close range is typically in a square next to you, and can
usually be attacked with melee weapons.

Near::
Opponents Near you are usually within 5 squares of you. This means that you can
take 5 Steps to move up to the opponent and attack with the Melee Combat skill.
Almost all ranged weapons can reach opponents Near you.  The GM should
determine the "range" of the Near distance on a per-encounter basis.

Far::
Opponents that are Far away from you can only be attacked with Ranged Combat.
It would require at least 15 Steps to reach such opponents.


NOTE: Environmental effects such as wind, rain, poor lighting, etc. can reduce
the range thresholds of the Near and Far distances. For instance, the GM might
rule that, for a given battle taking place during a thunderstorm at night, the
Near distance is 2 squares and the Far distance is 6 squares.

=== Stress

Damage, wounds, stress and strain are represented by Stress Points.  If a
character accumulates 10 Stress Points (this is called the Stress Threshold),
they receive a Consequence and reset their stress-counter. Stress points do not
carry over.

Armors can increase a character's stress threshold such that they
can accumulate more than 10 points of damage before suffering consequences.

Damage from _vorpal_ attacks are carried over and can therefore cause multiple
consequences from a single attack. Luckily vorpal attacks require special 
weapons and/or special heroic powerups.

Example:: If a character with 8 stress points receives additional 24 stress points
from a single strike, they get one consequence, and the stress counter is reset
to zero. Thus it would not have mattered if the character got a 2-point wound
or a 1000-point wound.

Example:: If a character with 8 stress points receives additional 24 stress
points from a single _vorpal_ attack, they get 3 consequences, and the stress
counter is now 2 (8 + 25 = 32 = 3 · consequence + 2 · stress).

Stress and consequences is a way of ensuring that characters do not get
one-shot-killed. Under normal circumstances, it would require a number of hits
to kill a character. Vorpal attacks ensure that certain rare kinds of attacks
can still kill a character in one go.

[%header,cols="1,5"]
.Stress and Consequences
|===
| Consequences  | Effect
| 0             | No effects, base die is nominal (usually d10).
| 1             | Base die is one step below nominal (usually d8).
| 2             | Base die is 2 steps below nominal (usually d6).
| 3             | Base die is 3 steps below nominal (usually d4).
| 4             | Unconsciousness.
| 6             | Death.
|===

NOTE:: Some NPCs can suffer more or fewer consequences, and some have higher or
lower stress thresholds than normal characters.


[appendix]
== Appendix


[index]
== Index
