= KISS RPG
:toc:
:sectnums:
:checkedbox: pass:normal[{startsb}&#10004;{endsb}]

Kiss is a set of simple and all-purpose tabletop role playing game rules.  Even
though this document is focussed on the classic medieval fantasy setting, these
rules are highly adaptable for most campaign types.

This work is licensed under a Creative Commons Attribution-ShareAlike 4.0
International License.footnote:[License: https://creativecommons.org/licenses/by-sa/4.0/]
You are free to share and adapt this material for any purpose, including
commercially, as long as you give attribution.

== Dice and Tests

To see if something succeeds, you roll a d10 (called the _base die_) against a
given target number, usually set by the GM. If you equal to or higher than the
target number, you succeed.

Base Die::
When you roll a 10 on your base die, you may roll it again and add the result.
You can do this as long as you keep rolling 10s. If your base die has been
modified (for instance, the base die is reduced as a consequence of damage and
stress), this rule still applies as long as you roll the highest possible
number on the die. Adding rerolls like this is called an _open-ended die_ or
exploding die.footnote:[Exploding Dice: https://anydice.com/articles/exploding-dice/]

NOTE: It is not just the base die that can be open ended. Certain traits,
powerups, abilities, equipment and karma uses can make dice open ended. If you
see a die notation with a `+` at the end of it, it means that the die is
open-ended.  For instance, `d6` just means you roll a d6, but `d6+` means you
roll an open- ended d6.

Skill Die::
When a hero is particularly good at doing a specific thing (fighting, swimming,
magic, etc.) she may add a skill die to her roll when she performs those
actions. This is referred to as a skill test. Unless otherwise specified, the
skill die is not open-ended.

Hero Die::
When a a hero has become sufficiently advanced and experienced, she gains the
ability to add a hero die to certain rolls. This number of sides on the hero
die depends on how experienced the hero is.


== Karma

Character begins every session with exactly 2 karma points (this is called the
_karma reset_).

If you fail a meaningful roll (i.e. one that actually affects you, the party
and/or the plot), you are awarded a karma point. There are many ways to spend
these points. Some of them are described below:

TIP: High powered campaigns might reset the karma to 3 or 4, while more
realistic campaigns might reset karma to 1 or 0. Some player groups might
prefer not to reset the karma pools at all, possibly imposing upper limits on
how many karma points a character can have.

Exploding roll::
At the cost of 1 karma, before you roll any dice, you can declare that you want
to make an exploding roll, meaning that all the dice rolled (base, skill, and
hero) are made open-ended. This can also be applied to damage tests and other
tests that are not normally open ended.

Make a roll _easier_::
At the cost of 2 karma, before you roll any dice, you can declare that you
want to make a test _easier_, meaning that you get roll the entire test twice,
and choose the best outcome. This must be declared _before_ the roll is made.

Make a roll _heroic_::
If you have a hero die, you can spend 1 karma point to add that hero die to
any roll you want. You must declare that you are making a heroic roll _before_
you roll any dice.

Redo a failed test::
At the cost of 3 karma, you can declare that you want to reroll a failed test.
This is be done _after_ the dice are rolled, but before the GM tells you
whether the test succeeded or not.

Learn from your failures::
At the end of a session, you can convert 10 karma points into 1 experience point.
This can only be done once per session. So even if you somehow have 100 karma
at the end of a session, you can still only convert 10 of them to XP.



== Traits

The first game-mechanical thing to do when creating a new character is to
describe her via traits. You must choose 3 positive traits and 1 negative
trait.

NOTE: In KISS, concepts like attributes, races, background, heritages, etc.
have been replaced by traits.


=== Positive traits

Connected::
Once per session, at the cost of 1 karma, you can declare that you have a vague
connection with someone (maybe you met them, briefly worked for them, etc.).
Additionally, when engaged in social challenges where you can invoke a common
mutual acquaintance, all your rolls are open-ended.

Captain::
You have access to the »Ship Owner« powerup.

Darkvision::
You can see in complete darkness, but only in shades of gray.

Famous::
Once per session, at the cost of 1 karma, you can declare that a given person
knows about you or your family and sees you in a positive light. This makes
all your subsequent social challenges against that person open-ended.

Sprinter::
During combat you can move extra squares at the cost of 1 karma point per
square.

Unencumbered::
You can carry 15 load points worth of gear instead of the usual 10.

[[magic-user]]Magic User::
You can cast magical spells.

Mnemonist::
You can accurately recall anything you have ever seen or heard at the cost of 2
karma point. It only costs you a single karma point to redo tests in challenges
that rely purely on your memory and experience.

Nightvision::
You can see as well in dim light such as starlight or moonlight as if it were
daylight.

Nimble::
Same effect as the »tiny« trait. A character that is both tiny and nimble will
be able to avoid two attacks per scene, provided you have karma to spend.

Overpowered::
You have 8 powerup slots instead of 6.

Polyglot::
When you hear or read a language that was not hitherto known by you, you can
declare that you are familiar with it, enabling you to read, write and speak
it. This can be done once per session and it costs 3 karma points.

Socialite::
Once per session you can overcome a challenge of trust or etiquette by invoking
your background and heritage. Doing so costs one karma point.

Street Smart::
It only costs you a single karma point to redo tests during challenges that
involve shady city connections, finding your way in cities, or evaluating black
market prices.

Strong::
Once per scene you may redo tests that relies heavily and primarily on your
bodily strength. Doing so costs 1 karma.

Stubborn::
When you have the “dying” condition, you are awake and conscious. You can take
actions like any normal character, but doing so costs a karma point.

Tiny::
Once per scene you can completely avoid an attack. If you declare your intent
to avoid the attack before the attacker rolls their dice it costs 2 karma
point. If you avoid the attack after the attacker rolls their dice it costs 3
karma points.

Tough::
Once per scene you can avoid avoid getting a Consequence from a single attack.
Instead of getting a wound and resetting your stress points, your stress points
are set to their maximum value, but you do not get the wound. Doing this costs
one karma point.

Wealthy::
§§§ How does wealth work when we don't use wealth?

Well-equipped::
§§§§ More weapons, better armor.

=== Negative Traits

Addicted::
You have an addiction (alcohol, drugs, sex, gambling). Once per session, at the
cost of 3 karma points, the GM can enforce your addiction to create a conflict,
problem or disadvantage to you or the party.

Diminutive::
The GM can make you reroll your base die in intimidation check in exchange for
1 karma points.

Favor::
You owe a favor to a powerful person, organization, or entity. Once per
session, at the cost of 3 karma points, the GM can invoke this debt to create a
conflict for you or your party.

Hunted::
You are hunted, wanted, or stalked by a creature, person, organization, or
entity. Once per session, at the cost of 3 karma points, the GM can invoke your
stalker or their underlings and create a conflict for you or your party.

Infamous::
Once per session, at the cost of 2 karma points, the GM can rule that you failed
a given social challenge because of your bad reputation.

Infirm::
You easily get sick. At the cost of 2 karma points the GM can make you reroll
the base die of a check to resist disease or poison. At the cost of 3 karma
points the GM can invoke your fragile health to create a situation that is
hazardous to you or your party.

Kleptomaniac::
You are addicted to stealing. Once per session, at the cost of 2 karma points,
the GM can enforce your obsession to create a potential conflict, problem or
disadvantage to you or the party.

Obsessed::
You are obsessed with a person, place, thing or phenomenon. Once per session,
at the cost of 3 karma points, The GM can enforce your obsession to create a
conflict, problem or disadvantage to you or the party.

Poor::
§§§ Not much stuff.

Short Legs::
You can only move 4 squares per round instead of 5.

Thickheaded::
Once per session, at the cost of 2 karma points, the GM can enforce your
stupidity and make you redo a relevant test.

Ugly::
Once per session, at the cost of 2 karma points, the GM can rule that you failed
a given social challenge because of your physical appearance.

Uncouth::
Once per scene, at the cost of 3 karma points, the GM can rule that you failed
a given social challenge due to your social ineptitude.

Underpowered::
You have 4 powerup slots instead of 6.

Weak::
You have trouble with forced marches, etc. At the cost of 3 karma points, the
GM can limit your ability to perform demanding physical tasks over long periods
of time. At the cost of 2 karma points the GM can enforce your weakness by
making you redo tests that relies heavily on endurance.


== Powerups

Having chocen traits, the second thing to do is to choose your powerups. You
have 6 powerup slots (meaning that you can choose up to 6 powerups). You get 10
experience points with which to purchase powerups. Each powerup has a
powerpoint cost.

NOTE: In KISS, concepts like money, gear, special items, contacts, special
abilities, spells, etc. are all considered powerups. When you gain experience
from adventuring, you can purchase additional powerups, or increase the oomph
of the ones you already have.


Lucky (XP cost: 2, 3, or 4)::
Your karma reset value is 3, 4, or 4.


Ship Owner (XP cost: 4, 5, or 6)::
You own a spaceship. The amount of XP you pay for this powerup determines the
size of the ship.

Hero Die (XP cost: 10, 14, 20, 28, 38, or 50)::
Gain a d4, d6, d8, d10, or d12 hero die.



== Skils

[%header,cols="1,6"]
.Skills
|===
| Skill         | Description
| Acrobatics    | Climb, jump, tumble and stunts.
| Analysis      | Research or investigate an area, item, situation, etc.
| Appraisal     | Estimate price and authenticity of artwork, gems, coins, weapons, armor, buildings, etc.
| Arcana        | Cast magical spells. You must have the *<<magic-user, Magic User>>* advantage to learn this skill.
| Athletics     | Run, march, swim, endure physical stress.
| [Craft]       | [craft] can be a craft, art or science such as alchemy, blacksmithing, carpentry, engineering, gambling, masonry or painting.
| Creature Lore | Guestimate an approximation of a key knowledge such as Movement Rate, Defense Points, Hit Points, an Attribute Score, Skill Score, etc.
| Deception     | Disguise, bluff, lie, impersonate.
| Dodge         | §§§§§
| Geography     | Travel routes, local area knowledge, imports/exports, local prices, local laws.
| Healing       | First Aid, identify diseases and poisons.
| History       | Local lore, ancient lore. Knowledge of the old gods, of ancient cultures, races heroes and items.
| Insight       | Gain insight into the motivations and feelings of another person.
| Melee         | Attack with melee weapons.
| Negotiation   | Intimidation, haggling, interrogation.
| Ranged        | Attack with ranged- and thrown weapons.
| Reputation    | §§§§§
| Riding        | Horses, stags, griffons.
| Stealth       | Hide, sneak, camouflage.
| Survival      | Hunting, gathering, direction sense.
| Thievery      | Pick locks, slight of hand.
| Willpower     | §§§§§
|===


== Gear

[%header, cols="4,4*^.^"]
.Weapons
|===
| Weapon                        | Load  | Close | Near  | Far

| Unarmed Combat                | 0     | 1     | -     | -
| Knuckledusters                | 1     | d4    | -     | -
| Knives                        | 1     | d4    | d4    | -
| Staves, clubs, batons         | 2     | d6    | -     | -
| Javelins                      | 1     | d4    | d6    | -
| Light swords, axes, spears    | 3     | d8    | -     | -
| Heavy swords, axes, polearms  | 4     | d10   | -     | -
| Short bows, light crossbows   | 2     | -     | d6    | d4
| Long bows, heavy crossbows    | 4     | -     | d10   | d8
| Slings, hand crossbows        | 0     | -     | d4    | -
| Musket pistols                | 1     | d6+   | d4    | -
| Scatterguns                   | 3     | d10+  | d4    | -
| Musket Rifles                 | 4     | 1d4   | d10+  | d6+
|===
NOTE: The `+` denotes that the die is open-ended.


[%header, cols="4,4*^.^"]
.Armors
|===
| Armor             | Load  | Stress    | Hit   |  Move

| Unarmored         | 0     | 10        | 8     | ±0
| Leather           | 1     | 11        | 8     | ±0
| Hide Armor        | 2     | 12        | 9     | -1
| Hardened Leather  | 1     | 13        | 8     | ±0
| Scale Mail        | 3     | 13        | 9     | ±0
| Chain Shirt       | 2     | 14        | 9     | -1
| Chain Mail        | 3     | 14        | 10    | -1
| Breastplate       | 3     | 14        | 11    | -2
| Banded Mail       | 4     | 15        | 11    | -2
| Half Plate        | 4     | 15        | 12    | -3
| Full Plate        | 5     | 15        | 13    | -3
| Shield            | 1     | ±0        | +1    | ± 0
| Helmet            | 1     | +1        | ±0    | ± 0
|===
